services:
  library-db:
    container_name: library-db
    
    image: postgres:16-alpine
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nitc
      - POSTGRES_DB=library_app
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library_app"]
      interval: 5s
      timeout: 5s
      retries: 10

  library-redis:
    container_name: library-redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  library-worker:
    container_name: library-worker
    
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - .:/app
    
    env_file: .env

    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:nitc@library-db:5432/library_app
    
    depends_on:
      library-db:
        condition: service_healthy
      library-redis:
        condition: service_started
    
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", '--reload']
    
    ports:
      - "${HOST_PORT:-8000}:8000"
    
    restart: unless-stopped

volumes:
  postgres_data:
