"""add google_try_count to books

Revision ID: 2a0fe573f25e
Revises: f2726f41b4fe
Create Date: 2026-07-08 13:03:06.493638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0fe573f25e'
down_revision: Union[str, Sequence[str], None] = 'f2726f41b4fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('google_try_count', sa.Integer(), nullable=True))
    op.execute("UPDATE books SET google_try_count = 0 WHERE google_try_count IS NULL")
    op.alter_column('books', 'google_try_count', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'google_try_count')
    # ### end Alembic commands ###
