"""cleanup fields added to metadata queue

Revision ID: 2ca996f4895c
Revises: ab6bfb6576f0
Create Date: 2026-06-08 12:09:49.564353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca996f4895c'
down_revision: Union[str, Sequence[str], None] = 'ab6bfb6576f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'in_progress', 'completed', 'failed', name='jobstatus').create(op.get_bind())
    
    op.add_column('metadata_queue', sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True))
    
    op.alter_column('metadata_queue', 'id',
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True)
    
    op.execute("ALTER TABLE metadata_queue ALTER COLUMN status DROP DEFAULT")

    op.alter_column('metadata_queue', 'status',
        existing_type=sa.TEXT(),
        type_=sa.Enum('pending', 'in_progress', 'completed', 'failed', name='jobstatus'),
        existing_nullable=False,
        postgresql_using='status::jobstatus'
    )

    op.execute("ALTER TABLE metadata_queue ALTER COLUMN status SET DEFAULT 'pending'::jobstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('metadata_queue', 'status',
        existing_type=sa.Enum('pending', 'in_progress', 'completed', 'failed', name='jobstatus'),
        type_=sa.TEXT(),
        existing_nullable=False
    )
    
    op.alter_column('metadata_queue', 'id',
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True
    )
    
    op.drop_column('metadata_queue', 'finished_at')
    
    sa.Enum('pending', 'in_progress', 'completed', 'failed', name='jobstatus').drop(op.get_bind())
    # ### end Alembic commands ###
