"""default 0 wasn't set ig

Revision ID: 43dff745f4dc
Revises: 0fe4da6af43e
Create Date: 2026-06-05 12:46:50.586121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43dff745f4dc'
down_revision: Union[str, Sequence[str], None] = '0fe4da6af43e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
