"""add full text search

Revision ID: 8cb19fefb0b7
Revises: 44c271c1bb6d
Create Date: 2026-06-05 08:42:57.138759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cb19fefb0b7'
down_revision: Union[str, Sequence[str], None] = '44c271c1bb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_books_search_vector', 'books', ['search_vector'], unique=False, postgresql_using='gin')
    # populate search vector
    op.execute("""
        UPDATE books
        SET search_vector =
            to_tsvector(
                'english',
                coalesce(title,'') || ' ' ||
                coalesce(array_to_string(author,' '),'') || ' ' ||
                coalesce(array_to_string(categories,' '),'') || ' ' ||
                coalesce(description,'')
            );
    """)
    #keep it updated automatically
    op.execute("""
        CREATE FUNCTION books_search_vector_update()
        RETURNS trigger AS $$
        BEGIN
            NEW.search_vector :=
                to_tsvector(
                'english',
                coalesce(NEW.title,'') || ' ' ||
                coalesce(array_to_string(NEW.author,' '),'') || ' ' ||
                coalesce(array_to_string(NEW.categories,' '),'') || ' ' ||
                coalesce(NEW.description,'')
            );
            RETURN NEW;
        END
        $$ LANGUAGE plpgsql;
        """)
    # trigger
    op.execute("""
        CREATE TRIGGER books_search_vector_trigger
        BEFORE INSERT OR UPDATE
        ON books
        FOR EACH ROW
        EXECUTE FUNCTION books_search_vector_update();
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    DROP TRIGGER IF EXISTS books_search_vector_trigger ON books;
    """)

    op.execute("""
    DROP FUNCTION IF EXISTS books_search_vector_update();
    """)
    op.drop_index('ix_books_search_vector', table_name='books', postgresql_using='gin')
    op.drop_column('books', 'search_vector')
    # ### end Alembic commands ###
