"""initial

Revision ID: cbfe79b20622
Revises: 
Create Date: 2026-06-04 19:59:40.533777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbfe79b20622'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('biblio_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('authors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('isbn', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('total_copies', sa.Integer(), nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=False),
    sa.Column('lib_copies', sa.Integer(), nullable=False),
    sa.Column('mat_copies', sa.Integer(), nullable=False),
    sa.Column('metadata_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('biblio_id')
    )
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=False)
    op.create_table('book_copies',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('biblio_id', sa.BigInteger(), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('acquisition_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callnumber', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['books.biblio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_copies')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
