"""add catalog books table

Revision ID: d15761081368
Revises: fbbb24dc8d8a
Create Date: 2026-06-19 06:21:22.995684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15761081368'
down_revision: Union[str, Sequence[str], None] = 'fbbb24dc8d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_books',
    sa.Column('course_id', sa.String(length=50), nullable=False),
    sa.Column('biblio_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['biblio_id'], ['books.biblio_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'biblio_id')
    )
    op.create_index('ix_catalog_books_biblio_id', 'catalog_books', ['biblio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_books_biblio_id', table_name='catalog_books')
    op.drop_table('catalog_books')
    # ### end Alembic commands ###
