"""added column search_string

Revision ID: f2726f41b4fe
Revises: 2e3f4a5b6c7d
Create Date: 2026-07-01 22:29:23.312833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2726f41b4fe'
down_revision: Union[str, Sequence[str], None] = '2e3f4a5b6c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_books', sa.Column('search_string', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog_books', 'search_string')
    # ### end Alembic commands ###
